version: '3.5'
services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=dede 
    ports:
      - "3306:3306"

  restapi:
    build: ./restapi-springboot
    environment:
      - MYSQL_HOST=dede_en2b-mysqldb-1 
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=root 
      - MYSQL_PORT=3306
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on: 
      - restapi