[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
A retail company is in the need for an online retail system that ensures the privacy of its users based on the Solid specification (not to be misinterpreted with the SOLID principles of Object Oriented Programming). We will call this app DeDe (Decentralized Delivery).

Moreover, this will be ensured with the utilization of Solid Pods; a specification that lets people store their data securely in decentralized data stores. This grants the user total control of the data that is exposed using this retail service delivery, since they can concede or revoke access when needed (and the app will not store personal info). 


=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

.These are the main requirements of the application:
 * Emulation of an online shopping system where the user can select and order products.
** Like any other web app but in a reduced way.
 * Calculation of the delivery cost based on the address of the user in their Pod.
 ** The cost is based on an external API.
 * Simulation of the process of buying a product.
 ** The user can buy a product and add it to the shopping cart.
 ** There is a list of products for the user to buy.
 * Allowing the user to access the orders previously done.
 ** Like checking the search history in your browser.
 * Implementation using React and Typescript.
 ** This will be for the front-end, for the back-end we will use other frameworks such as SpringBoot.
 * The aplication should be accessible and deployed using a continuous integration system. 
 ** That means having a hosting service in which we can access the service.


=== Quality Goals

[options="header",cols="1,2,2"]
.Quality Goals, ordered by priority, with the most important ones being on top
|===
|Number|Quality|Motivation
| 1 | Privacy | The task to be done requires the use of SOLID, whose purpose is to secure the data of the users, so no one that is not authorized should be able to access that information.
| 2 | Usability | The application can be used in an easy and intuitive manner, for all kinds of users.
| 3 | Performance | The software should be fast and have as least response time as possible.
| 4 | Availability | The system should be able to be used for as much time as possible.
|===

=== Stakeholders

[options="header",cols="1,2,2,2"]
.Stakeholders
|===
|Role/Name|Contact|Description|Expectations
| Students | Diego Martín Fernández +
 Laura Pernía Blanco +
 Stelian Adrian Stanci | The members of the team that is going to develop this project. | They are expected to deliver a functional version of this product with the use of several different technologies, and which meets the stated requirements.
| Teachers | Pablo González González +
 José Emilio Labra Gallo | Qualified instructors who are able to teach, guide, and supervise students throughout the development process. | The teachers are expected to evaluate the work of the students and to help them achieve their objective.
| Users | | The ones that will make use of the application. | They are expected to use the application for some purpose, and possibly to even give feedback about it.
| Related companies | Inrupt\Empathy | Companies that have contributed to the creation of the SOLID Challenge, which is closely related to this project. | They promote the SOLID Challenge, help solving errors through its forum, and reward the winning project.
|===