[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
We divide the constrains into two parts: technical and business constrains.

=== Technical constrains

[role="arc42help"]
****
.Contents
The technical constrains for the development of the system.

.Motivation
Know the fixed technical constrains for the system.

.Form
Table with all the technical constrains and its corresponding description .
****
Technical constrains are those that are fixed technical constrains decisions. Most of them appear in the description of the system.

[options="header",cols="1,2"]
|===
|Constraint|Description
| _React_ | React defines itself JavaScript library for building user interfaces. The application has to be implemented usint React
| _TypeScript_ | TypeScript is a strongly typed programming language that builds on JavaScript. 
| _SOLID principles_|Solid is a specification that lets people store their data securely in decentralized data stores called Pods. When data is stored in someone's Pod, they control its access.
| _Continuous integration system_|The application has to be accessible and deployed using a continuous integration system.
| _Keep track of orders done_|The system has to allow users to visualize the orders done, so it has to keep track of them.
|===

=== Business constrains

[role="arc42help"]
****
.Contents
The business constrains for the development of the system.

.Motivation
Know the business constrains for the system.

.Form
Table with all the business constrains and its corresponding description .
****
The business constrains are those decisions affecting the software architecture design or that will affect future decisions.

[options="header",cols="1,2"]
|===
|Constraint|Description
| _GitHub_|The code has to be deployed in GitHub, a public repository.
| _Schedule_ | The system has to be finished by the 13th week of the laboratory, with deliveries by the 4th, the 7th and the 10th weeks.
| _Team_| The team is composed by five people.
| _Students_| All of us are students with more subjects and projects, so we can not dedicate full time to the project.
|===
