[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

=== Risks

The risks that we might find during the development of the project are the following (ordered by priority):

.Risks
[%header, cols=2]
|===
| Risk | Remediation
| Small team | Prioritize the most important things, as we will probably not have much time to do several extra things
| Lack of time | Be as effective as possible with the time we have, keep realistic expectations of what we can achieve
in a given span of time
| No previous knowledge of React, Typescript nor SOLID | Spend some time learning the basics of this technologies,
and build upon that basis to get the knowledge required for working with these technologies in our project
|===

Now we talk about some technical debts, that are also ordered by importance

.Technical debts
[%header, cols=2]
|===
| Debt | Explanation

| Using Springboot and MySQL technologies | At the beginning of the project they looked like a good choice as many
members of the team had some experience working with them, but as it progressed we started having some problems, that
would not have happened using other technologies.
| Not validating user input | Due to the lack of time and with the goal of achieving a functional application in a short
period of time, we did not pay enough attention to user input, that should be validated to a bigger extent to preserve security.
| Code good practices | In some parts of the code we have neglected code quality (as in the use of suitable design patterns and code
design) to obtain a functional product faster. Since we had no prior experience using React nor Typescript, we don't really know all
the good practises and most optimal way of coding with them, so it would have taken us a lot of time to be proficient.
| Hardcoded credentials | He have hardcoded credentials in the code, which constitute a very serious security problem. As this is not
a real project and we only use sandbox/free services we decided to leave them that way in order to spend more time in more critical
aspects of the functionality.
| Lack of some tests | We didn't have enough time to perform integration and load test, so there might be problems we are not aware of
that we may have noticed when doing such tests.
|===
